name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-05"
usage_model = "bundled"
env = { }
routes = [
  { pattern = "chat.gzhu.app", custom_domain = true }
]

kv_namespaces = [
  { binding = "kv", id = "652e5c6c1d5643d9863a63b1f9ef9558" }
]

[triggers]
crons = [ ]
